### ISSUE TITLE
Non-static method amilna\versioning\components\Libs::mkView()

### ISSUE THREAD

**Issue by evgenmil** [amilna/versioning#1]
Hello! After installing the module error appears:
"Non-static method amilna\versioning\components\Libs::mkView() should not be called statically, assuming $this from incompatible context"

Please help solve the problem.
Thanking you in advance!

**Comment by aaiyo** [comment]
Hi thank you for the report, i have made some little updates. Please let me know if it is doesn't work :)

**Comment by evgenmil** [comment]
thank you. I also made some changes. In particular array_agg not found, replaced the group_concat

**Comment by aaiyo** [comment]
your right it's a solution when use mysql :+1:
