### ISSUE TITLE
Apply version has problem

### ISSUE THREAD

**Issue by evgenmil** [amilna/versioning#2]
I want to open another question. When you click on Apply version, there is an error "Getting unknown property: yii \ behaviors \ TimestampBehavior :: leftAttribute"

I have a connection in the model behavior TimestampBehavior. How to fix bugs compatibility?
![screenshot - 15_04](https://cloud.githubusercontent.com/assets/6258440/7152841/9a8fab2e-e364-11e4-834d-7f9ebda64be8.png)

Thanking you in advance!

**Comment by aaiyo** [comment]
i think it is caused by the timestamp behavior not configured with an index name, so the if clause ($k == "tree") doesn't work. So i've changed it to ($k === "tree"), i hope it work for you. Thanks again for your report.

**Comment by evgenmil** [comment]
Thank you fix this problem
